version: 2

updates:
  #  Check all submodule dependencies every week (Fridays at 6PM MT / 1AM UTC)
  - package-ecosystem: "gitsubmodule"
    schedule:
        interval: "weekly"
        day: "friday"
        time: "01:00"
    directory: "/"
  # Maintain dependencies for GitHub Actions once a month
  - package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"
    directory: "/"
