version: 2

updates:
  #  Check all submodule dependencies every week (Fridays at 6PM MT / Saturdays at 1AM UTC)
  - package-ecosystem: "gitsubmodule"
    schedule:
        interval: "weekly"
        day: "saturday"
        time: "01:00"
    directory: "/"
    commit-message:
      # Prefix all commit messages with "[refs #0] " to satisfy CIVET ticket requirement
      prefix: "[refs #0] "
    allow:
      # Allow updates for crane and squirrel....moose is updated through CIVET
      - dependency-name: "crane"
      - dependency-name: "squirrel"
  # Maintain dependencies for GitHub Actions once a month
  - package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"
    directory: "/"
