blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/shannon-lab/zapdos/discussions
    about: Ask general questions about Zapdos and discuss with other Zapdos community members.
