Content:
    Zapdos:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
            - templates/stubs/*

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: Zapdos

Extensions:
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
